name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 
  build:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      
      - name: Docker Setup QEMU
        
        # uses: docker/setup-qemu-action@6520a2d2cb6db42c90c297c8025839c98e531268
        uses: docker/setup-qemu-action@v1.0.1
        id: qemu
        with:
          # QEMU static binaries Docker image (e.g. tonistiigi/binfmt:latest)
          #image: # optional, default is tonistiigi/binfmt:latest
          # Platforms to install (e.g. arm64,riscv64,arm)
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x # optional, default is all
          
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
          
      - name: Docker Setup Buildx
        
        # uses: docker/setup-buildx-action@154c24e1f33dbb5865a021c99f1318cfebf27b32
        uses: docker/setup-buildx-action@v1.1.1
        with:
         
          install: true # optional, default is false
          
          
      - name: Docker Login
        
        # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        uses: docker/login-action@v1.8.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          #registry: # optional
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_USERNAME }} # optional

          password: ${{ secrets.DOCKER_PASSWORD }} # optional
          
      - name: Build and push Docker images
        
        # uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
        uses: docker/build-push-action@v2.3.0
        with:
          tags: ${{ secrets.DOCKER_USER }}/docker-base:latest # optional
          platforms: ${{ steps.qemu.outputs.platforms }} # optional
          push: true # optional, default is false
          