name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build the Docker image
        run: >-
          echo ".git" > .dockerignore
          
          docker buildx build . --file Dockerfile --compress --no-cache --rm --force-rm --push
          --platform linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          --build-arg VCS_REF=`git rev-parse --short HEAD`
          --build-arg VCS_URL=`git remote get-url origin`
          --build-arg VERSION="1.0"
          --build-arg TIMEZONE="Asia/Kathmandu"
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/docker-base:latest
          
          docker buildx imagetools inspect ${{ secrets.DOCKERHUB_USERNAME }}/docker-base:latest
